spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  main:
    allow-bean-definition-overriding: true

jwt:
  rsa-private-key: ${JWT_RSA_PRIVATE_KEY}
  rsa-public-key: ${JWT_RSA_PUBLIC_KEY}

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
        web: TRACE
        security: DEBUG